### ISSUE TITLE
Massive memory consuming when require('opentype.js') is run

### ISSUE THREAD

**Issue by minsikim** [nodebox/opentype.js#333]
Massive memory consuming when require('opentype.js') is run
I'm trying to use this library, but when I add
`const opentype = require('opentype.js');`
to my code. and It runs. it consumes all of my memory 5.6GB and it crashes.

I'm on a Electron project.
I tried the code in the Main process and the renderer process and within the html code.
All the same problem happens.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Jolg42** [comment]
Hi @minsikim 

Interesting... Actually we just released 0.8.0 so maybe you could try to install the precedent version 0.7.3 and let us know if you have the same issue?

**Comment by minsikim** [comment]
@Jolg42 Thank you for the fast response

Unfortunately, I just tried out 0.7.3 and It's still not working. both Windows and Mac.
I think something is looping through... and it's definitely an Electron + Opentype.js issue.
I tried to import only  opentype.Font as well. but it also seems to take all memory possible.

**Comment by Jolg42** [comment]
I won't have the time to investigate this issue unfortunately but you should add a link to you repository if it's public as an example.

I guess the best way to know what's happening will be to record the memory consumption and see where it's being allocated.

You could try:
https://electronjs.org/docs/tutorial/debugging-main-process
https://github.com/sindresorhus/electron-debug

**Comment by minsikim** [comment]
Solved it by detuoring opentype variable through main process
and passing it with `remote` module in electron

```
//in electron main process
global.opentype = require('opentype.js');
let mainWindow = new BrowserWindow();
mainWindow.webContents.send('init-opentype', opentype);
```

```
//in renderer process
var opentype = remote.getGlobal('opentype');
console.log(opentype);
>>Object {…}, BoundingBox:(...), Font:(...), Glyph:(...), Path:(...), load:(...).....
```

but still not sure why it doesn't work directly in the renderer process
I'll notify when it all clears up.

@Jolg42 thanks again for advice

**Comment by minsikim** [comment]
I investigated this problem a little bit more.
(I wanted to use `const opentype = require('opentype.js');` for performance's sake)

I tried versions through 0.5.0 ~ 0.8.0(opentype.js)
This problem happens from 0.7.2 ~0.8.0
I think it may be an issue from bundling configuration.(by rollup.js)
(not sure specifically, never used rollup.js before)

electron has a different process layer compared to plain old web apps
I suspect that something maybe causing infinite loops while loading the module.

**Comment by Jolg42** [comment]
@minsikim Indeed I found the circular dependency when I updated Rollup.

Could you try to use the version from that branch https://github.com/nodebox/opentype.js/tree/circular-dep-fix and let me if it works for you?

**Comment by minsikim** [comment]
I tried [https://github.com/nodebox/opentype.js/tree/circular-dep-fix](url),
unfortunately it's not working yet.

**Comment by Jolg42** [comment]
😞 Well I merged it in master. _(Btw, I edited your previous comments because the url were broken.)_

**Comment by ardentia** [comment]
This issue is old and I don't know if it has been already investigated but I can confirm that opentype consumes quite a lot of memory when loaded. For context, I am using [pdfjs](https://www.npmjs.com/package/pdfjs) which depends on opentype. Currently installed opentype version is: 1.3.4

![chrome_ZwLFOSCqDK](https://github.com/opentypejs/opentype.js/assets/41083417/789c98b7-6f0d-4d76-8e10-c1bba188fd38)

**Comment by Connum** [comment]
@ardentia Thanks for the update! Could you somehow test using the current master? 1.3.4 is quite old but there hasn't been a new release to npm yet.

**Comment by ardentia** [comment]
@Connum thanks for the quick reply. I uninstalled `opentype.js@1.3.4` and instead installed the master branch, so now the entry in `package.json` looks like this:

```
"opentype.js": "github:opentypejs/opentype.js",
```

I assumed that the `bin` dir contains whatever is needed for the project to work out of the box, so I didn't run any build scripts. Let me know if I missed anything.

The allocation timeline snapshot with the latest master looks like this:

![chrome_qYncazk9BS](https://github.com/opentypejs/opentype.js/assets/41083417/c870e8b2-4b1e-43f5-bc28-77550faf8a5f)

To be fair, the shallow size this time is bit less but it still seems to be a lot.

I took a look at the `pdfjs` implementation and it also requires the `opentype` package the same way @minsikim did initially:
https://github.com/rkusa/pdfjs/blob/b6cdd70c64611d0e1369ad928028b2cf51009379/lib/font/otf.js#L3
